version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/wallet
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3000:3000"

volumes:
  postgres_data: